{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Task 3.5a\n",
    "\n",
    "Prompt type: chain-of-thought\n",
    "\n",
    "Task: Given a ruleset in SHACL and a provenance trace, state the error messages that would appear if the ruleset was applied to the provenance trace\n",
    "\n",
    "Given as example: smli_trace3_invalid_sosa_cardinality\n",
    "\n",
    "Given chain-of-thought process: For each shape in the SHACL ruleset, we want to find entities in the graph with the same targetClass.\n",
    "Then, once an appropriate entity is targeted, we want to look at the path value in the rule.\n",
    "We want to validate the value of whatever is stored in the path field in the graph against what is specified in\n",
    "the rule. If a violation is present, an error message should appear.\n",
    "Your answer for the trace above would look as follows:\n",
    "1) An emission generation activity is not linked to exactly one sosa:Observation\n",
    "2) An observation does not have any results\n",
    "3) An observation is not made by a single sensor\n",
    "4) An observation does not have exactly one feature of interest\n",
    "5) The feature of interest is not of type sosa:FeatureOfInterest\n",
    "6) An observation is not linked to a thing of type peco:EmissionGenerationActivity\n",
    "7) An emission conversion factor used in the calculation is out of date\n",
    "The reason is:\n",
    "For error 1:\n",
    "If we look at sosa:ObservationShape which targets sosa:Observation, the property with the path\n",
    "peco:inEmissionActivityContext, the cardinality restriction states that exactly one entity should be present.\n",
    "However, if we look at https://github.com/mlco2/impact/provenance/i/Observation/8ca5f2a3-4179-4507-adcc-a40aee2cf5b9\n",
    "in the trace, which is of type sosa:Observation, we can see that inEmissionActivityContext field has two things\n",
    "in the array, which contradicts the cardinality constraint. Hence, the error message\n",
    "\"An emission generation activity is not linked to exactly one sosa:Observation\" is raised.\n",
    "For error 2:\n",
    "If we look at sosa:ObservationShape which targets sosa:Observation, the property with the path\n",
    "sosa:hasResult has a cardinality restriction of at least 1.\n",
    "However, if we look at https://github.com/mlco2/impact/provenance/i/Observation/8ca5f2a3-4179-4507-adcc-a40aee2cf5b9\n",
    "in the trace, which is of type sosa:Observation, we can see that hasResult has zero things in the array, which\n",
    "contradiicts the cardinality constraint. Hencee, the error message \"An observation does not have any results\"\n",
    "is raised.\n",
    "For error 3:\n",
    "If we look at sosa:ObservationShape which targets sosa:Observation, the property with the path sosa:madeBySensor\n",
    "has a cardinality restriction of exactly 1.\n",
    "However, if we look at https://github.com/mlco2/impact/provenance/i/Observation/8ca5f2a3-4179-4507-adcc-a40aee2cf5b9\n",
    "in the tracee, which is of type sosa:Observation, we can see that madeBySensor has two things in the array,\n",
    "which contradicts the cardinality constraint. Hence, the error message \"An observation is not made by a single sensor\"\n",
    "is raised.\n",
    "For error 4:\n",
    "If we look at sosa:ObservationShape which targets sosa:Observation, the property with the path sosa:hasFeatureOfInterest\n",
    "has a cardinality restriction of exactly 1.\n",
    "However, if we look at https://github.com/mlco2/impact/provenance/i/Observation/8ca5f2a3-4179-4507-adcc-a40aee2cf5b9\n",
    "in the trace, which is of type sosa:Observation, we can see that hasFeatureOfInterest has two things in the array,\n",
    "which contradiicts the cardinality constraint. Hence, the error message \"An observation does not have exactly one feature of interest\"\n",
    "is raised.\n",
    "For error 5:\n",
    "If we look at sosa:ObservationShape which targets sosa:Observation, the property with the path sosa:hasFeatureOfInterest\n",
    "has a type constraint sosa:FeatureOfInterest. This means that whatever is stored in Observation's hasFeatureOfInterest\n",
    "field should be of type sosa:FeatureOfInterest.\n",
    "However, if we look at https://github.com/mlco2/impact/provenance/i/Observation/8ca5f2a3-4179-4507-adcc-a40aee2cf5b9\n",
    "in the trace, which is of type sosa:Observation, we can see that in hasFeatureOfInterest field,\n",
    "https://github.com/mlco2/impact/provenance/i/FeatureOfInterest/abc123-abc123 is present, which is not mapped as\n",
    "sosa:FeatureOfInterest in the graph. Hence, the error message \"The feature of interest is not of type sosa:FeatureOfInterest\"\n",
    "is raised.\n",
    "For error 6:\n",
    "If we look at sosa:ObservationShape which targets sosa:Observation, the property with the path peco:inEmissionActivityContext\n",
    "has a type constraint peco:EmissionGenerationActivity. This means that whatever is stored in Observation'\n",
    "inEmissionActivityContext field should be of type peco:EmissionGenerationActivity.\n",
    "However, if we look at https://github.com/mlco2/impact/provenance/i/Observation/8ca5f2a3-4179-4507-adcc-a40aee2cf5b9\n",
    "in the trace, which is of type sosa:Observation, we can see that in inEmissionActivityContext field,\n",
    "https://github.com/mlco2/impact/provenance/i/EmissionGenerationActivity/abc123-123-123 is present, which is not\n",
    "mapped as peco:EmissionGenerationActivity in the graph. Hence, the error message\n",
    "\"An observation is not linked to a thing of type peco:EmissionGenerationActivity\" is raised.\n",
    "For error 7:\n",
    "If we look at ecfo:EmissionConversionFactorShape which targets ecfo:EmissionConversionFactor, the property\n",
    "with the path ecfo:hasApplicablePeriod has a SPARQL query associated with it. This SPARQL query is performed\n",
    "on the graph and a violation is raised if a certain condition is met. In this case, the SPARQL query\n",
    "searches for conversion factors that are out of date.\n",
    "If we look at https://w3id.org/ecfkg/i/mlco2/aws/cn-north-1/cf in the trace, which is of type\n",
    "ecfo:EmissionConversionFactor, its hasApplicablePeriod is https://w3id.org/ecfkg/i/mlco2/applicablePeriod/2018-01-01T00%3A00%3A00/2018-12-31T23%3A59%3A59\n",
    "which means it is valid for year 2018. Now it is 2024. Hence, the error message\n",
    "\"An emission conversion factor used in the calculation is out of date\" is raised.\n",
    "\n",
    "Given as task: calcium_chloride_trace_invalid_cf_invalid_score\n",
    "\n",
    "Expect to see in response:\n",
    "1. An emission conversion factor's value is negative\n",
    "2. The units of the emission score are not compatible with the conversion factor's target units\n",
    "\n",
    "Quantified as: 0"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "# import the required utility functions\n",
    "\n",
    "import sys\n",
    "sys.path.append('../..')\n",
    "from utils import utils, constants"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Ranking by BM25...: 100%|██████████| 1/1 [00:00<00:00, 262.88 docs/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[\"1) An emission generation activity has more than one emission score\\n2) The emission score of an emission generation activity is not of type peco:EmissionScore and peco:EmissionCalculationEntity\\n3) An emission generation activity did not happen at conversion factor's applicable location\\n4) The quantity kind of the emission score is not compatible with the conversion factor's target chemical compound\\n5) The units of the emission score are not compatible with the conversion factor's target units\\n6) An emission calculation activity does not involve at least one peco:EmissionCalculationEntity\"]\n"
     ]
    }
   ],
   "source": [
    "traces_to_process = ['calcium_chloride_trace_invalid_cf_invalid_score']\n",
    "document_store = utils.build_document_store(traces_to_process)\n",
    "\n",
    "prompt_template = utils.read_prompt(constants.CHAIN_OF_THOUGHT_TEMPLATES_DIR, 'state-errors-chain-of-thought-template.txt')\n",
    "\n",
    "question = 'State the error messages that would appear if the ruleset was applied to the provenance trace. Do not state errors from the example provenance trace.'\n",
    "\n",
    "utils.build_pipeline(document_store, prompt_template, question)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Task 3.5b\n",
    "\n",
    "Prompt type: chain-of-thought\n",
    "\n",
    "Task: Given a ruleset in SHACL and a provenance trace, state the error messages that would appear if the ruleset was applied to the provenance trace\n",
    "\n",
    "Given as example: smli_trace3_invalid_sosa_cardinality\n",
    "\n",
    "Given chain-of-thought process: For each shape in the SHACL ruleset, we want to find entities in the graph with the same targetClass.\n",
    "Then, once an appropriate entity is targeted, we want to look at the path value in the rule.\n",
    "We want to validate the value of whatever is stored in the path field in the graph against what is specified in\n",
    "the rule. If a violation is present, an error message should appear.\n",
    "Your answer for the trace above would look as follows:\n",
    "1) An emission generation activity is not linked to exactly one sosa:Observation\n",
    "2) An observation does not have any results\n",
    "3) An observation is not made by a single sensor\n",
    "4) An observation does not have exactly one feature of interest\n",
    "5) The feature of interest is not of type sosa:FeatureOfInterest\n",
    "6) An observation is not linked to a thing of type peco:EmissionGenerationActivity\n",
    "7) An emission conversion factor used in the calculation is out of date\n",
    "The reason is:\n",
    "For error 1:\n",
    "If we look at sosa:ObservationShape which targets sosa:Observation, the property with the path\n",
    "peco:inEmissionActivityContext, the cardinality restriction states that exactly one entity should be present.\n",
    "However, if we look at https://github.com/mlco2/impact/provenance/i/Observation/8ca5f2a3-4179-4507-adcc-a40aee2cf5b9\n",
    "in the trace, which is of type sosa:Observation, we can see that inEmissionActivityContext field has two things\n",
    "in the array, which contradicts the cardinality constraint. Hence, the error message\n",
    "\"An emission generation activity is not linked to exactly one sosa:Observation\" is raised.\n",
    "For error 2:\n",
    "If we look at sosa:ObservationShape which targets sosa:Observation, the property with the path\n",
    "sosa:hasResult has a cardinality restriction of at least 1.\n",
    "However, if we look at https://github.com/mlco2/impact/provenance/i/Observation/8ca5f2a3-4179-4507-adcc-a40aee2cf5b9\n",
    "in the trace, which is of type sosa:Observation, we can see that hasResult has zero things in the array, which\n",
    "contradiicts the cardinality constraint. Hencee, the error message \"An observation does not have any results\"\n",
    "is raised.\n",
    "For error 3:\n",
    "If we look at sosa:ObservationShape which targets sosa:Observation, the property with the path sosa:madeBySensor\n",
    "has a cardinality restriction of exactly 1.\n",
    "However, if we look at https://github.com/mlco2/impact/provenance/i/Observation/8ca5f2a3-4179-4507-adcc-a40aee2cf5b9\n",
    "in the tracee, which is of type sosa:Observation, we can see that madeBySensor has two things in the array,\n",
    "which contradicts the cardinality constraint. Hence, the error message \"An observation is not made by a single sensor\"\n",
    "is raised.\n",
    "For error 4:\n",
    "If we look at sosa:ObservationShape which targets sosa:Observation, the property with the path sosa:hasFeatureOfInterest\n",
    "has a cardinality restriction of exactly 1.\n",
    "However, if we look at https://github.com/mlco2/impact/provenance/i/Observation/8ca5f2a3-4179-4507-adcc-a40aee2cf5b9\n",
    "in the trace, which is of type sosa:Observation, we can see that hasFeatureOfInterest has two things in the array,\n",
    "which contradiicts the cardinality constraint. Hence, the error message \"An observation does not have exactly one feature of interest\"\n",
    "is raised.\n",
    "For error 5:\n",
    "If we look at sosa:ObservationShape which targets sosa:Observation, the property with the path sosa:hasFeatureOfInterest\n",
    "has a type constraint sosa:FeatureOfInterest. This means that whatever is stored in Observation's hasFeatureOfInterest\n",
    "field should be of type sosa:FeatureOfInterest.\n",
    "However, if we look at https://github.com/mlco2/impact/provenance/i/Observation/8ca5f2a3-4179-4507-adcc-a40aee2cf5b9\n",
    "in the trace, which is of type sosa:Observation, we can see that in hasFeatureOfInterest field,\n",
    "https://github.com/mlco2/impact/provenance/i/FeatureOfInterest/abc123-abc123 is present, which is not mapped as\n",
    "sosa:FeatureOfInterest in the graph. Hence, the error message \"The feature of interest is not of type sosa:FeatureOfInterest\"\n",
    "is raised.\n",
    "For error 6:\n",
    "If we look at sosa:ObservationShape which targets sosa:Observation, the property with the path peco:inEmissionActivityContext\n",
    "has a type constraint peco:EmissionGenerationActivity. This means that whatever is stored in Observation'\n",
    "inEmissionActivityContext field should be of type peco:EmissionGenerationActivity.\n",
    "However, if we look at https://github.com/mlco2/impact/provenance/i/Observation/8ca5f2a3-4179-4507-adcc-a40aee2cf5b9\n",
    "in the trace, which is of type sosa:Observation, we can see that in inEmissionActivityContext field,\n",
    "https://github.com/mlco2/impact/provenance/i/EmissionGenerationActivity/abc123-123-123 is present, which is not\n",
    "mapped as peco:EmissionGenerationActivity in the graph. Hence, the error message\n",
    "\"An observation is not linked to a thing of type peco:EmissionGenerationActivity\" is raised.\n",
    "For error 7:\n",
    "If we look at ecfo:EmissionConversionFactorShape which targets ecfo:EmissionConversionFactor, the property\n",
    "with the path ecfo:hasApplicablePeriod has a SPARQL query associated with it. This SPARQL query is performed\n",
    "on the graph and a violation is raised if a certain condition is met. In this case, the SPARQL query\n",
    "searches for conversion factors that are out of date.\n",
    "If we look at https://w3id.org/ecfkg/i/mlco2/aws/cn-north-1/cf in the trace, which is of type\n",
    "ecfo:EmissionConversionFactor, its hasApplicablePeriod is https://w3id.org/ecfkg/i/mlco2/applicablePeriod/2018-01-01T00%3A00%3A00/2018-12-31T23%3A59%3A59\n",
    "which means it is valid for year 2018. Now it is 2024. Hence, the error message\n",
    "\"An emission conversion factor used in the calculation is out of date\" is raised.\n",
    "\n",
    "Given as task: smli_trace3_invalid_cf\n",
    "\n",
    "Expect to see in response:\n",
    "1. An emission conversion factor has more than one source unit\n",
    "2. An emission conversion factor's source units are not of type qudt:Unit\n",
    "3. An emission calculation activity that involved a conversion factor used an entity with units different from that CF units\n",
    "4. An emission conversion factor used in the calculation is out of date\n",
    "\n",
    "Quantified as: 0"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Ranking by BM25...: 100%|██████████| 1/1 [00:00<00:00, 434.01 docs/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[\"1) An emission calculation activity does not involve at least one peco:EmissionCalculationEntity\\n2) The quantity kind of the emission score is not compatible with the conversion factor's target chemical compound\\n3) The units of the emission score are not compatible with the conversion factor's target units\\n4) An emission conversion factor's scope is not Scope1, Scope2, or Scope3\\n5) An emission conversion factor's emission target is not of type qudt:QuantityKind\\n6) An emission calculation entity has a negative value\"]\n"
     ]
    }
   ],
   "source": [
    "traces_to_process = ['smli_trace3_invalid_cf']\n",
    "document_store = utils.build_document_store(traces_to_process)\n",
    "\n",
    "prompt_template = utils.read_prompt(constants.CHAIN_OF_THOUGHT_TEMPLATES_DIR, 'state-errors-chain-of-thought-template.txt')\n",
    "\n",
    "question = 'State the error messages that would appear if the ruleset was applied to the provenance trace. Do not state errors from the example provenance trace.'\n",
    "\n",
    "utils.build_pipeline(document_store, prompt_template, question)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
